export const DEFAULT_PAGINATION_OFFSET = 0;
export const DEFAULT_PAGINATION_LIMIT = 20;
export const DEFAULT_PAGINATION = {
  limit: DEFAULT_PAGINATION_LIMIT,
  offset: DEFAULT_PAGINATION_OFFSET,
};

export const TABLE_STATE_STORAGE_KEY = 'tableState';
export const DEFAULT_DEBOUNCE_TIMEOUT = 500;
